### ISSUE TITLE
TypeError: QuestAnswer1Doc.__init__() got an unexpected keyword argument 'use_quest_eval'

### ISSUE THREAD

**Issue by songkq** [IAAR-Shanghai/CRUD_RAG#2]
@zhiyulee-RUC Hi, could you please give some advice for this issue?

```
CUDA_VISIBLE_DEVICES="0" python3 -u quick_start.py --task 'all' \
     --model_name qwen-7b --temperature 0.1 --max_new_tokens 1280 \
     --data_path 'data/crud_split/split_merged.json' --docs_path 'data/80000_docs' --docs_type 'txt' --shuffle True \
     --chunk_size 128 --chunk_overlap 0 --retriever_name 'base' --retrieve_top_k 8 \
     --collection_name 'docs_80k_chuncksize_128_0' --num_threads 32 \
     --embedding_name 'models/bge-base-zh-v1.5' --embedding_dim 768 \
     --quest_eval --bert_score_eval --construct_index --show_progress_bar True > logs/eval-qwen-7b-docs_80k_chuncksize_128_0.log 2>&1 & 
```

```
Indexing of part 872000 finished!
DEBUG:pymilvus.milvus_client.milvus_client:Created new connection using: d9fe48bcc77e40b984fe17ed5291e687
Indexing finished!
Traceback (most recent call last):
  File "/workspace/Benchmark/public/CRUD_RAG/quick_start.py", line 104, in <module>
    'quest_answer': [QuestAnswer1Doc, QuestAnswer2Docs, QuestAnswer3Docs],
  File "/workspace/Benchmark/public/CRUD_RAG/quick_start.py", line 104, in <listcomp>
    'quest_answer': [QuestAnswer1Doc, QuestAnswer2Docs, QuestAnswer3Docs],
TypeError: QuestAnswer1Doc.__init__() got an unexpected keyword argument 'use_quest_eval'
```

**Comment by haruhi-sudo** [comment]
Hello, Thanks for your feedback. We have fixed the bugs in the code. If you still have some questions, please contact us via email s1583050085@gmail.com.
